version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    target-branch: "main"
    open-pull-requests-limit: 10
    versioning-strategy: increase
    schedule:
      interval: "daily"
      timezone: "Asia/Tokyo"
    ignore:
      - dependency-name: "rails"
        update-types: ["version-update:semver-major"]
      - dependency-name: "puma"
        update-types: ["version-update:semver-major"]
