openapi: "3.0.0"
info:
  title: rails_postgres api
  version: "1.0"
servers:
  - url: "http://localhost:3000"
paths:
  /_healthcheck:
    get:
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                properties:
                  message:
                    type: string
